[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
actix-rt = "2.7.0"
aws-config = "0.51.0"
aws-sdk-dynamodb = "0.21.0"
async-trait = "0.1.59"
chrono = "0.4.23"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
log = "0.4.17"
env_logger = "0.10.0"


# aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
# aws-sdk-dynamodb = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
# aws-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
# aws-smithy-client = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", features = [
#   "client-hyper",
#   "rustls",
#   "rt-tokio",
# ] }
# aws-smithy-http = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next", features = [
#   "rt-tokio",
# ] }
# aws-smithy-types = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }




lambda_http = "0.7"
lambda_runtime = "0.7"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
dotenv = "0.15.0"
envy = "0.4.2"
jsonwebtoken = "8.2.0"
tracing-actix-web = "0.6.2"
actix-cors = "0.6.4"
futures-util = "0.3.25"
rustc-serialize = "0.3.24"
derive_more = "0.99.17"
rand = "0.8.5"
rust-argon2 = "1.0.0"

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
