[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
actix-rt = "2.7.0"
aws-config = "0.51.0"
aws-sdk-dynamodb = "0.21.0"
async-trait = "0.1.59"
chrono = "0.4.23"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
log = "0.4.17"
env_logger = "0.10.0"