[workspace]

members = [
    "lib_users",
    "lib_config",
    "lib_licenses",
    "lib_util_jwt",
    "lambda_login",
    "lambda_user",
    "lambda_license",
    "lambda_admin",
    "server_http",
    "command_tables"
]


