version: '3.8'
services:
  #dynamodb-local:
  #  image: amazon/dynamodb-local:latest
  #  ports:
  #    - "8000:8000"

  localstack-pro:
    #container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-pro:latest  # required for Pro
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (required for Pro)
    environment:
      - DEBUG=1
      - LS_LOG=info #error,debug,info,trace, trace-internal
      - PERSISTENCE=0 #set to 1 if you want to keep changes between restarts
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # required for Pro
      - LAMBDA_DOCKER_FLAGS=-p 127.0.0.1:5050:5050 # debug port
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./.localstack-pro:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"  



  localstack-community: #https://www.bitovi.com/blog/running-aws-resources-on-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      #- "4510-4559:4510-4559"  # external services port range
    environment:
      #- SERVICES=dynamodb,s3,lambda,iam,secretsmanager,sns,apigateway,logs,kms
      - DEBUG=1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      #- AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=./.localstack
    volumes:
      - "./.localstack-community:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./create-docker-resources.sh:/docker-entrypoint-initaws.d/create-docker-resources.sh"

  # blockchain:
  #   build: 
  #     context: .
  #     dockerfile: ./lib_blockchain/res/ganache/Dockerfile
  #   ports:
  #     - "8545:8545"

  quickwit:
    image: quickwit/quickwit:latest
    command: run
    restart: always
    environment:
      QW_ENABLE_OTLP_ENDPOINT: true 
      QW_ENABLE_JAEGER_ENDPOINT: true 
    ports:
      - '7280:7280'
      - '7281:7281'
    volumes:
      - ./qwdata:/quickwit/qwdata

  jaeger:
    image: jaegertracing/jaeger-query:latest
    restart: always
    depends_on:
      - quickwit
    environment:
      SPAN_STORAGE_TYPE: 'grpc-plugin'
      GRPC_STORAGE_SERVER: 'quickwit:7281'
    ports:
      - '16686:16686'

  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    user: root
    depends_on:
      - quickwit
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: 'quickwit-quickwit-datasource'
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana 

