[package]
name="lib_util_jwt"
version="0.0.1"
edition = "2021"

[lib]
name="lib_util_jwt"
crate-type=["lib"]


[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
chrono = "0.4.31"
jsonwebtoken = "9.1.0"
http = "0.2.9"
