[package]
name="lib_util_jwt"
version="0.0.1"
edition = "2021"

[lib]
name="lib_util_jwt"
crate-type=["lib"]


[dependencies]
#env_logger = "0.10.0"
#dotenv = "0.15.0"
#envy = "0.4.2"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
chrono = "0.4.23"
#actix-web = "4.2.1"
jsonwebtoken = "8.2.0"
http = "0.2.8"
