[package]
name="lib_util_jwt"
version="0.0.1"
edition = "2021"

[lib]
name="lib_util_jwt"
crate-type=["lib"]


[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
chrono = "0.4.31"
jsonwebtoken = "8.3.0"
http = "0.2.9"
