[package]
name="lib_licenses"
version="0.0.1"
edition = "2021"
autotests = false

[lib]
name="lib_licenses"
crate-type=["lib"]

[[test]]
name="integration"
path="tests/lib.rs"


[dependencies]
lib_config = { path = "../lib_config" }
log = "0.4.17"
chrono = {version="0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
rust-argon2 = "1.0.0"
aws-config = "0.54.1"
aws-sdk-dynamodb = "0.24.0"
async-trait = "0.1.63"
tracing = { version = "0.1", features = ["log"] }
validator = { version = "0.16", features = ["derive"] }
http = "0.2.8"
http-serde = "1.1.2"
url = {version="2.3.1", features=["serde"] }
ethers = "1.0.2"
hex = "0.4.3"
web3 = "0.18.0"
hex-literal = "0.3.4"

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]

[dev-dependencies]
env_logger = "0.10.0"
aws-types = "0.54.1"
spectral = "0.6.0"
testcontainers = "0.14.0"
tokio = { version="1.24.2", features=["macros"]}
lib_config = { path = "../lib_config" }
lib_licenses = { path= "./"}
