[package]
name="lib_users"
version="0.0.1"
edition = "2021"

[lib]
name="lib_users"
crate-type=["lib"]


[dependencies]
lib_config = { path = "../lib_config" }

chrono = {version="0.4.23", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
rust-argon2 = "1.0.0"
aws-config = "0.54.1"
aws-sdk-dynamodb = "0.24.0"
async-trait = "0.1.63"
tracing = { version = "0.1", features = ["log"] }
tokio =  { version="1.24.2", features = ["macros"] }
validator = { version = "0.16", features = ["derive"] }
regex = "1.7.1"
zxcvbn = "2.2.1"

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
