swagger: "2.0"
info:
  version: "0.0.1"
  title: Truly API
# during dev, should point to your local machine
host: eu-stage.truly.video
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /swagger:
    x-swagger-pipe: swagger_raw
  /auth/signup:
    post:
      operationId: 'createUser'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'User object to be created'
          required: true
          schema:
            $ref: '#/definitions/NewUser'
      responses:
        "200":
          description: A new user has been created successfully
        "500":
          description: System error
          
  /hello:
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:

  NewUser:
    type: 'object'
    description: This object describes a new user in the system. It accepts email or device fields. Only if email is provided, the password is mandatory.
    properties: 
      email:
        type: 'string'
        example: 'test1@test1.er.io'
      password:
        type: 'string'
        example: 'Ay7pert&*fg'
        description: minium lenght 12 characters, simbols, mayus,...
      device:
        type: 'string'
        example: 'd4567-1234-1234-1234-1234-4567'

  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
