name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:

    runs-on: ubuntu-latest

    #defaults:
    #  run:
    #    working-directory: ./lambdas

    steps:
    - uses: actions/checkout@v3
    - name: install cargo lambda
      run: pip3 install cargo-lambda
    - name: Build
      run: cargo lambda build --release --all-features --arm64 --output-format zip --workspace  --exclude server_*  --exclude command_* --lambda-dir target/lambda_arm64 
    - name: Configure AWS Credentials  
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_API_KEY }}
    - name: Terraform init
      working-directory: ./terraform
      run: terraform init
    - name: Terraform plan
      working-directory: ./terraform
      run: terraform plan
    - name: Terraform apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

